# Generated by Django 5.2.14 on 2026-06-06 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chlore_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('chef_centre', 'Chef Centre'), ('agent', 'Agent Exploitation'), ('consultation', 'Consultation')], default='agent', max_length=20),
        ),
    ]
