# Generated by Django 5.2.14 on 2026-06-06 14:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chlore_api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_serie', models.CharField(max_length=100, unique=True)),
                ('code_qr', models.CharField(max_length=200, unique=True)),
                ('etat', models.CharField(choices=[('plein', 'Plein'), ('branche', 'Branché'), ('vide', 'Vide'), ('remplissage', 'En remplissage'), ('entretien', 'En entretien'), ('epreuve', 'En épreuve'), ('bloque', 'Bloqué')], default='plein', max_length=20)),
                ('capacite_kg', models.IntegerField(choices=[(50, '50 kg'), (1000, '1 tonne')], default=50)),
                ('date_derniere_epreuve', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('centre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipients', to='chlore_api.centre')),
            ],
        ),
        migrations.CreateModel(
            name='Mouvement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ancien_etat', models.CharField(max_length=20)),
                ('nouvel_etat', models.CharField(max_length=20)),
                ('observation', models.TextField()),
                ('date_heure', models.DateTimeField(auto_now_add=True)),
                ('synced', models.BooleanField(default=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('centre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chlore_api.centre')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements', to='recipients.recipient')),
            ],
            options={
                'ordering': ['-date_heure'],
            },
        ),
    ]
