# Generated by Django 5.2.14 on 2026-06-10 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigPeriodicite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_heure', models.DateTimeField(auto_now_add=True)),
                ('capacite_kg', models.IntegerField(unique=True)),
                ('periodicite_mois', models.IntegerField()),
                ('description', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ['-date_heure'],
            },
        ),
        migrations.AlterModelOptions(
            name='mouvement',
            options={},
        ),
    ]
