# Generated by Django 5.2.14 on 2026-06-11 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipients', '0002_configperiodicite_alter_mouvement_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configperiodicite',
            options={},
        ),
        migrations.AlterModelOptions(
            name='mouvement',
            options={'ordering': ['-date_heure']},
        ),
        migrations.RemoveField(
            model_name='configperiodicite',
            name='date_heure',
        ),
        migrations.AddField(
            model_name='recipient',
            name='fournisseur',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
