# Generated by Django 5.2.14 on 2026-07-05 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipients', '0004_anomalie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipient',
            name='capacite_kg',
            field=models.IntegerField(choices=[(50, '50 kg'), (400, '400 kg'), (900, '900 kg')], default=50),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='etat',
            field=models.CharField(choices=[('plein', 'Plein'), ('branche', 'Branché'), ('vide', 'Vide'), ('remplissage', 'En remplissage'), ('entretien', 'En entretien'), ('epreuve', 'En épreuve')], default='plein', max_length=20),
        ),
    ]
