# Generated by Django 5.2.14 on 2026-07-12 00:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chlore_api', '0002_alter_user_managers_alter_user_role'),
        ('recipients', '0005_alter_recipient_capacite_kg_alter_recipient_etat'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='mouvement',
            index=models.Index(fields=['recipient', 'date_heure'], name='recipients__recipie_f75860_idx'),
        ),
        migrations.AddIndex(
            model_name='recipient',
            index=models.Index(fields=['centre', 'etat'], name='recipients__centre__1fb713_idx'),
        ),
    ]
