# Generated by Django 5.2.14 on 2026-07-12 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chlore_api', '0002_alter_user_managers_alter_user_role'),
        ('recipients', '0006_mouvement_recipients__recipie_f75860_idx_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='recipient',
            constraint=models.CheckConstraint(condition=models.Q(('etat__in', ['plein', 'branche', 'vide', 'remplissage', 'entretien', 'epreuve'])), name='etat_valide'),
        ),
        migrations.AddConstraint(
            model_name='recipient',
            constraint=models.CheckConstraint(condition=models.Q(('capacite_kg__in', [50, 400, 900])), name='capacite_valide'),
        ),
    ]
