# Generated by Django 5.2.14 on 2026-07-12 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipients', '0007_recipient_etat_valide_recipient_capacite_valide'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipient',
            name='config_periodicite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='recipients.configperiodicite'),
        ),
    ]
